/*
 * Mealapp api descriptor
 * This is a meal app android client.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: palko9711@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mobilsoftlab.mealapp.network.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Meal
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-28T10:10:39.282Z")
public class Meal {
  @SerializedName("idMeal")
  private String idMeal = null;

  @SerializedName("strMeal")
  private String strMeal = null;

  @SerializedName("strMealThumb")
  private String strMealThumb = null;

  public Meal idMeal(String idMeal) {
    this.idMeal = idMeal;
    return this;
  }

   /**
   * Get idMeal
   * @return idMeal
  **/
  @ApiModelProperty(value = "")
  public String getIdMeal() {
    return idMeal;
  }

  public void setIdMeal(String idMeal) {
    this.idMeal = idMeal;
  }

  public Meal strMeal(String strMeal) {
    this.strMeal = strMeal;
    return this;
  }

   /**
   * Get strMeal
   * @return strMeal
  **/
  @ApiModelProperty(value = "")
  public String getStrMeal() {
    return strMeal;
  }

  public void setStrMeal(String strMeal) {
    this.strMeal = strMeal;
  }

  public Meal strMealThumb(String strMealThumb) {
    this.strMealThumb = strMealThumb;
    return this;
  }

   /**
   * Get strMealThumb
   * @return strMealThumb
  **/
  @ApiModelProperty(value = "")
  public String getStrMealThumb() {
    return strMealThumb;
  }

  public void setStrMealThumb(String strMealThumb) {
    this.strMealThumb = strMealThumb;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Meal meal = (Meal) o;
    return Objects.equals(this.idMeal, meal.idMeal) &&
        Objects.equals(this.strMeal, meal.strMeal) &&
        Objects.equals(this.strMealThumb, meal.strMealThumb);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idMeal, strMeal, strMealThumb);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Meal {\n");
    
    sb.append("    idMeal: ").append(toIndentedString(idMeal)).append("\n");
    sb.append("    strMeal: ").append(toIndentedString(strMeal)).append("\n");
    sb.append("    strMealThumb: ").append(toIndentedString(strMealThumb)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

