/*
 * Mealapp api descriptor
 * This is a meal app android client.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: palko9711@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mobilsoftlab.mealapp.network.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.mobilsoftlab.mealapp.network.io.swagger.client.model.MealDetails;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MealList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-28T10:10:39.282Z")
public class MealList {
  @SerializedName("meals")
  private List<MealDetails> meals = null;

  public MealList meals(List<MealDetails> meals) {
    this.meals = meals;
    return this;
  }

  public MealList addMealsItem(MealDetails mealsItem) {
    if (this.meals == null) {
      this.meals = new ArrayList<MealDetails>();
    }
    this.meals.add(mealsItem);
    return this;
  }

   /**
   * Get meals
   * @return meals
  **/
  @ApiModelProperty(value = "")
  public List<MealDetails> getMeals() {
    return meals;
  }

  public void setMeals(List<MealDetails> meals) {
    this.meals = meals;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MealList mealList = (MealList) o;
    return Objects.equals(this.meals, mealList.meals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meals);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MealList {\n");
    
    sb.append("    meals: ").append(toIndentedString(meals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

