/*
 * Mealapp api descriptor
 * This is a meal app android client.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: palko9711@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mobilsoftlab.mealapp.network.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MealDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-28T10:10:39.282Z")
public class MealDetails {
  @SerializedName("idMeal")
  private String idMeal = null;

  @SerializedName("strMeal")
  private String strMeal = null;

  @SerializedName("strDrinkAlternate")
  private String strDrinkAlternate = null;

  @SerializedName("strCategory")
  private String strCategory = null;

  @SerializedName("strArea")
  private String strArea = null;

  @SerializedName("strInstructions")
  private String strInstructions = null;

  @SerializedName("strMealThumb")
  private String strMealThumb = null;

  @SerializedName("strTags")
  private String strTags = null;

  @SerializedName("strYoutube")
  private String strYoutube = null;

  @SerializedName("strIngredient1")
  private String strIngredient1 = null;

  @SerializedName("strIngredient2")
  private String strIngredient2 = null;

  @SerializedName("strIngredient3")
  private String strIngredient3 = null;

  @SerializedName("strIngredient4")
  private String strIngredient4 = null;

  @SerializedName("strIngredient5")
  private String strIngredient5 = null;

  @SerializedName("strIngredient6")
  private String strIngredient6 = null;

  @SerializedName("strIngredient7")
  private String strIngredient7 = null;

  @SerializedName("strIngredient8")
  private String strIngredient8 = null;

  @SerializedName("strIngredient9")
  private String strIngredient9 = null;

  @SerializedName("strIngredient10")
  private String strIngredient10 = null;

  @SerializedName("strIngredient11")
  private String strIngredient11 = null;

  @SerializedName("strIngredient12")
  private String strIngredient12 = null;

  @SerializedName("strIngredient13")
  private String strIngredient13 = null;

  @SerializedName("strIngredient14")
  private String strIngredient14 = null;

  @SerializedName("strIngredient15")
  private String strIngredient15 = null;

  @SerializedName("strIngredient16")
  private String strIngredient16 = null;

  @SerializedName("strIngredient17")
  private String strIngredient17 = null;

  @SerializedName("strIngredient18")
  private String strIngredient18 = null;

  @SerializedName("strIngredient19")
  private String strIngredient19 = null;

  @SerializedName("strIngredient20")
  private String strIngredient20 = null;

  @SerializedName("strMeasure1")
  private String strMeasure1 = null;

  @SerializedName("strMeasure2")
  private String strMeasure2 = null;

  @SerializedName("strMeasure3")
  private String strMeasure3 = null;

  @SerializedName("strMeasure4")
  private String strMeasure4 = null;

  @SerializedName("strMeasure5")
  private String strMeasure5 = null;

  @SerializedName("strMeasure6")
  private String strMeasure6 = null;

  @SerializedName("strMeasure7")
  private String strMeasure7 = null;

  @SerializedName("strMeasure8")
  private String strMeasure8 = null;

  @SerializedName("strMeasure9")
  private String strMeasure9 = null;

  @SerializedName("strMeasure10")
  private String strMeasure10 = null;

  @SerializedName("strMeasure11")
  private String strMeasure11 = null;

  @SerializedName("strMeasure12")
  private String strMeasure12 = null;

  @SerializedName("strMeasure13")
  private String strMeasure13 = null;

  @SerializedName("strMeasure14")
  private String strMeasure14 = null;

  @SerializedName("strMeasure15")
  private String strMeasure15 = null;

  @SerializedName("strMeasure16")
  private String strMeasure16 = null;

  @SerializedName("strMeasure17")
  private String strMeasure17 = null;

  @SerializedName("strMeasure18")
  private String strMeasure18 = null;

  @SerializedName("strMeasure19")
  private String strMeasure19 = null;

  @SerializedName("strMeasure20")
  private String strMeasure20 = null;

  @SerializedName("strSource")
  private String strSource = null;

  @SerializedName("strImageSource")
  private String strImageSource = null;

  @SerializedName("strCreativeCommonsConfirmed")
  private String strCreativeCommonsConfirmed = null;

  @SerializedName("dateModified")
  private String dateModified = null;

  public MealDetails idMeal(String idMeal) {
    this.idMeal = idMeal;
    return this;
  }

   /**
   * Get idMeal
   * @return idMeal
  **/
  @ApiModelProperty(value = "")
  public String getIdMeal() {
    return idMeal;
  }

  public void setIdMeal(String idMeal) {
    this.idMeal = idMeal;
  }

  public MealDetails strMeal(String strMeal) {
    this.strMeal = strMeal;
    return this;
  }

   /**
   * Get strMeal
   * @return strMeal
  **/
  @ApiModelProperty(value = "")
  public String getStrMeal() {
    return strMeal;
  }

  public void setStrMeal(String strMeal) {
    this.strMeal = strMeal;
  }

  public MealDetails strDrinkAlternate(String strDrinkAlternate) {
    this.strDrinkAlternate = strDrinkAlternate;
    return this;
  }

   /**
   * Get strDrinkAlternate
   * @return strDrinkAlternate
  **/
  @ApiModelProperty(value = "")
  public String getStrDrinkAlternate() {
    return strDrinkAlternate;
  }

  public void setStrDrinkAlternate(String strDrinkAlternate) {
    this.strDrinkAlternate = strDrinkAlternate;
  }

  public MealDetails strCategory(String strCategory) {
    this.strCategory = strCategory;
    return this;
  }

   /**
   * Get strCategory
   * @return strCategory
  **/
  @ApiModelProperty(value = "")
  public String getStrCategory() {
    return strCategory;
  }

  public void setStrCategory(String strCategory) {
    this.strCategory = strCategory;
  }

  public MealDetails strArea(String strArea) {
    this.strArea = strArea;
    return this;
  }

   /**
   * Get strArea
   * @return strArea
  **/
  @ApiModelProperty(value = "")
  public String getStrArea() {
    return strArea;
  }

  public void setStrArea(String strArea) {
    this.strArea = strArea;
  }

  public MealDetails strInstructions(String strInstructions) {
    this.strInstructions = strInstructions;
    return this;
  }

   /**
   * Get strInstructions
   * @return strInstructions
  **/
  @ApiModelProperty(value = "")
  public String getStrInstructions() {
    return strInstructions;
  }

  public void setStrInstructions(String strInstructions) {
    this.strInstructions = strInstructions;
  }

  public MealDetails strMealThumb(String strMealThumb) {
    this.strMealThumb = strMealThumb;
    return this;
  }

   /**
   * Get strMealThumb
   * @return strMealThumb
  **/
  @ApiModelProperty(value = "")
  public String getStrMealThumb() {
    return strMealThumb;
  }

  public void setStrMealThumb(String strMealThumb) {
    this.strMealThumb = strMealThumb;
  }

  public MealDetails strTags(String strTags) {
    this.strTags = strTags;
    return this;
  }

   /**
   * Get strTags
   * @return strTags
  **/
  @ApiModelProperty(value = "")
  public String getStrTags() {
    return strTags;
  }

  public void setStrTags(String strTags) {
    this.strTags = strTags;
  }

  public MealDetails strYoutube(String strYoutube) {
    this.strYoutube = strYoutube;
    return this;
  }

   /**
   * Get strYoutube
   * @return strYoutube
  **/
  @ApiModelProperty(value = "")
  public String getStrYoutube() {
    return strYoutube;
  }

  public void setStrYoutube(String strYoutube) {
    this.strYoutube = strYoutube;
  }

  public MealDetails strIngredient1(String strIngredient1) {
    this.strIngredient1 = strIngredient1;
    return this;
  }

   /**
   * Get strIngredient1
   * @return strIngredient1
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient1() {
    return strIngredient1;
  }

  public void setStrIngredient1(String strIngredient1) {
    this.strIngredient1 = strIngredient1;
  }

  public MealDetails strIngredient2(String strIngredient2) {
    this.strIngredient2 = strIngredient2;
    return this;
  }

   /**
   * Get strIngredient2
   * @return strIngredient2
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient2() {
    return strIngredient2;
  }

  public void setStrIngredient2(String strIngredient2) {
    this.strIngredient2 = strIngredient2;
  }

  public MealDetails strIngredient3(String strIngredient3) {
    this.strIngredient3 = strIngredient3;
    return this;
  }

   /**
   * Get strIngredient3
   * @return strIngredient3
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient3() {
    return strIngredient3;
  }

  public void setStrIngredient3(String strIngredient3) {
    this.strIngredient3 = strIngredient3;
  }

  public MealDetails strIngredient4(String strIngredient4) {
    this.strIngredient4 = strIngredient4;
    return this;
  }

   /**
   * Get strIngredient4
   * @return strIngredient4
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient4() {
    return strIngredient4;
  }

  public void setStrIngredient4(String strIngredient4) {
    this.strIngredient4 = strIngredient4;
  }

  public MealDetails strIngredient5(String strIngredient5) {
    this.strIngredient5 = strIngredient5;
    return this;
  }

   /**
   * Get strIngredient5
   * @return strIngredient5
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient5() {
    return strIngredient5;
  }

  public void setStrIngredient5(String strIngredient5) {
    this.strIngredient5 = strIngredient5;
  }

  public MealDetails strIngredient6(String strIngredient6) {
    this.strIngredient6 = strIngredient6;
    return this;
  }

   /**
   * Get strIngredient6
   * @return strIngredient6
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient6() {
    return strIngredient6;
  }

  public void setStrIngredient6(String strIngredient6) {
    this.strIngredient6 = strIngredient6;
  }

  public MealDetails strIngredient7(String strIngredient7) {
    this.strIngredient7 = strIngredient7;
    return this;
  }

   /**
   * Get strIngredient7
   * @return strIngredient7
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient7() {
    return strIngredient7;
  }

  public void setStrIngredient7(String strIngredient7) {
    this.strIngredient7 = strIngredient7;
  }

  public MealDetails strIngredient8(String strIngredient8) {
    this.strIngredient8 = strIngredient8;
    return this;
  }

   /**
   * Get strIngredient8
   * @return strIngredient8
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient8() {
    return strIngredient8;
  }

  public void setStrIngredient8(String strIngredient8) {
    this.strIngredient8 = strIngredient8;
  }

  public MealDetails strIngredient9(String strIngredient9) {
    this.strIngredient9 = strIngredient9;
    return this;
  }

   /**
   * Get strIngredient9
   * @return strIngredient9
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient9() {
    return strIngredient9;
  }

  public void setStrIngredient9(String strIngredient9) {
    this.strIngredient9 = strIngredient9;
  }

  public MealDetails strIngredient10(String strIngredient10) {
    this.strIngredient10 = strIngredient10;
    return this;
  }

   /**
   * Get strIngredient10
   * @return strIngredient10
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient10() {
    return strIngredient10;
  }

  public void setStrIngredient10(String strIngredient10) {
    this.strIngredient10 = strIngredient10;
  }

  public MealDetails strIngredient11(String strIngredient11) {
    this.strIngredient11 = strIngredient11;
    return this;
  }

   /**
   * Get strIngredient11
   * @return strIngredient11
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient11() {
    return strIngredient11;
  }

  public void setStrIngredient11(String strIngredient11) {
    this.strIngredient11 = strIngredient11;
  }

  public MealDetails strIngredient12(String strIngredient12) {
    this.strIngredient12 = strIngredient12;
    return this;
  }

   /**
   * Get strIngredient12
   * @return strIngredient12
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient12() {
    return strIngredient12;
  }

  public void setStrIngredient12(String strIngredient12) {
    this.strIngredient12 = strIngredient12;
  }

  public MealDetails strIngredient13(String strIngredient13) {
    this.strIngredient13 = strIngredient13;
    return this;
  }

   /**
   * Get strIngredient13
   * @return strIngredient13
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient13() {
    return strIngredient13;
  }

  public void setStrIngredient13(String strIngredient13) {
    this.strIngredient13 = strIngredient13;
  }

  public MealDetails strIngredient14(String strIngredient14) {
    this.strIngredient14 = strIngredient14;
    return this;
  }

   /**
   * Get strIngredient14
   * @return strIngredient14
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient14() {
    return strIngredient14;
  }

  public void setStrIngredient14(String strIngredient14) {
    this.strIngredient14 = strIngredient14;
  }

  public MealDetails strIngredient15(String strIngredient15) {
    this.strIngredient15 = strIngredient15;
    return this;
  }

   /**
   * Get strIngredient15
   * @return strIngredient15
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient15() {
    return strIngredient15;
  }

  public void setStrIngredient15(String strIngredient15) {
    this.strIngredient15 = strIngredient15;
  }

  public MealDetails strIngredient16(String strIngredient16) {
    this.strIngredient16 = strIngredient16;
    return this;
  }

   /**
   * Get strIngredient16
   * @return strIngredient16
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient16() {
    return strIngredient16;
  }

  public void setStrIngredient16(String strIngredient16) {
    this.strIngredient16 = strIngredient16;
  }

  public MealDetails strIngredient17(String strIngredient17) {
    this.strIngredient17 = strIngredient17;
    return this;
  }

   /**
   * Get strIngredient17
   * @return strIngredient17
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient17() {
    return strIngredient17;
  }

  public void setStrIngredient17(String strIngredient17) {
    this.strIngredient17 = strIngredient17;
  }

  public MealDetails strIngredient18(String strIngredient18) {
    this.strIngredient18 = strIngredient18;
    return this;
  }

   /**
   * Get strIngredient18
   * @return strIngredient18
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient18() {
    return strIngredient18;
  }

  public void setStrIngredient18(String strIngredient18) {
    this.strIngredient18 = strIngredient18;
  }

  public MealDetails strIngredient19(String strIngredient19) {
    this.strIngredient19 = strIngredient19;
    return this;
  }

   /**
   * Get strIngredient19
   * @return strIngredient19
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient19() {
    return strIngredient19;
  }

  public void setStrIngredient19(String strIngredient19) {
    this.strIngredient19 = strIngredient19;
  }

  public MealDetails strIngredient20(String strIngredient20) {
    this.strIngredient20 = strIngredient20;
    return this;
  }

   /**
   * Get strIngredient20
   * @return strIngredient20
  **/
  @ApiModelProperty(value = "")
  public String getStrIngredient20() {
    return strIngredient20;
  }

  public void setStrIngredient20(String strIngredient20) {
    this.strIngredient20 = strIngredient20;
  }

  public MealDetails strMeasure1(String strMeasure1) {
    this.strMeasure1 = strMeasure1;
    return this;
  }

   /**
   * Get strMeasure1
   * @return strMeasure1
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure1() {
    return strMeasure1;
  }

  public void setStrMeasure1(String strMeasure1) {
    this.strMeasure1 = strMeasure1;
  }

  public MealDetails strMeasure2(String strMeasure2) {
    this.strMeasure2 = strMeasure2;
    return this;
  }

   /**
   * Get strMeasure2
   * @return strMeasure2
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure2() {
    return strMeasure2;
  }

  public void setStrMeasure2(String strMeasure2) {
    this.strMeasure2 = strMeasure2;
  }

  public MealDetails strMeasure3(String strMeasure3) {
    this.strMeasure3 = strMeasure3;
    return this;
  }

   /**
   * Get strMeasure3
   * @return strMeasure3
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure3() {
    return strMeasure3;
  }

  public void setStrMeasure3(String strMeasure3) {
    this.strMeasure3 = strMeasure3;
  }

  public MealDetails strMeasure4(String strMeasure4) {
    this.strMeasure4 = strMeasure4;
    return this;
  }

   /**
   * Get strMeasure4
   * @return strMeasure4
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure4() {
    return strMeasure4;
  }

  public void setStrMeasure4(String strMeasure4) {
    this.strMeasure4 = strMeasure4;
  }

  public MealDetails strMeasure5(String strMeasure5) {
    this.strMeasure5 = strMeasure5;
    return this;
  }

   /**
   * Get strMeasure5
   * @return strMeasure5
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure5() {
    return strMeasure5;
  }

  public void setStrMeasure5(String strMeasure5) {
    this.strMeasure5 = strMeasure5;
  }

  public MealDetails strMeasure6(String strMeasure6) {
    this.strMeasure6 = strMeasure6;
    return this;
  }

   /**
   * Get strMeasure6
   * @return strMeasure6
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure6() {
    return strMeasure6;
  }

  public void setStrMeasure6(String strMeasure6) {
    this.strMeasure6 = strMeasure6;
  }

  public MealDetails strMeasure7(String strMeasure7) {
    this.strMeasure7 = strMeasure7;
    return this;
  }

   /**
   * Get strMeasure7
   * @return strMeasure7
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure7() {
    return strMeasure7;
  }

  public void setStrMeasure7(String strMeasure7) {
    this.strMeasure7 = strMeasure7;
  }

  public MealDetails strMeasure8(String strMeasure8) {
    this.strMeasure8 = strMeasure8;
    return this;
  }

   /**
   * Get strMeasure8
   * @return strMeasure8
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure8() {
    return strMeasure8;
  }

  public void setStrMeasure8(String strMeasure8) {
    this.strMeasure8 = strMeasure8;
  }

  public MealDetails strMeasure9(String strMeasure9) {
    this.strMeasure9 = strMeasure9;
    return this;
  }

   /**
   * Get strMeasure9
   * @return strMeasure9
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure9() {
    return strMeasure9;
  }

  public void setStrMeasure9(String strMeasure9) {
    this.strMeasure9 = strMeasure9;
  }

  public MealDetails strMeasure10(String strMeasure10) {
    this.strMeasure10 = strMeasure10;
    return this;
  }

   /**
   * Get strMeasure10
   * @return strMeasure10
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure10() {
    return strMeasure10;
  }

  public void setStrMeasure10(String strMeasure10) {
    this.strMeasure10 = strMeasure10;
  }

  public MealDetails strMeasure11(String strMeasure11) {
    this.strMeasure11 = strMeasure11;
    return this;
  }

   /**
   * Get strMeasure11
   * @return strMeasure11
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure11() {
    return strMeasure11;
  }

  public void setStrMeasure11(String strMeasure11) {
    this.strMeasure11 = strMeasure11;
  }

  public MealDetails strMeasure12(String strMeasure12) {
    this.strMeasure12 = strMeasure12;
    return this;
  }

   /**
   * Get strMeasure12
   * @return strMeasure12
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure12() {
    return strMeasure12;
  }

  public void setStrMeasure12(String strMeasure12) {
    this.strMeasure12 = strMeasure12;
  }

  public MealDetails strMeasure13(String strMeasure13) {
    this.strMeasure13 = strMeasure13;
    return this;
  }

   /**
   * Get strMeasure13
   * @return strMeasure13
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure13() {
    return strMeasure13;
  }

  public void setStrMeasure13(String strMeasure13) {
    this.strMeasure13 = strMeasure13;
  }

  public MealDetails strMeasure14(String strMeasure14) {
    this.strMeasure14 = strMeasure14;
    return this;
  }

   /**
   * Get strMeasure14
   * @return strMeasure14
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure14() {
    return strMeasure14;
  }

  public void setStrMeasure14(String strMeasure14) {
    this.strMeasure14 = strMeasure14;
  }

  public MealDetails strMeasure15(String strMeasure15) {
    this.strMeasure15 = strMeasure15;
    return this;
  }

   /**
   * Get strMeasure15
   * @return strMeasure15
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure15() {
    return strMeasure15;
  }

  public void setStrMeasure15(String strMeasure15) {
    this.strMeasure15 = strMeasure15;
  }

  public MealDetails strMeasure16(String strMeasure16) {
    this.strMeasure16 = strMeasure16;
    return this;
  }

   /**
   * Get strMeasure16
   * @return strMeasure16
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure16() {
    return strMeasure16;
  }

  public void setStrMeasure16(String strMeasure16) {
    this.strMeasure16 = strMeasure16;
  }

  public MealDetails strMeasure17(String strMeasure17) {
    this.strMeasure17 = strMeasure17;
    return this;
  }

   /**
   * Get strMeasure17
   * @return strMeasure17
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure17() {
    return strMeasure17;
  }

  public void setStrMeasure17(String strMeasure17) {
    this.strMeasure17 = strMeasure17;
  }

  public MealDetails strMeasure18(String strMeasure18) {
    this.strMeasure18 = strMeasure18;
    return this;
  }

   /**
   * Get strMeasure18
   * @return strMeasure18
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure18() {
    return strMeasure18;
  }

  public void setStrMeasure18(String strMeasure18) {
    this.strMeasure18 = strMeasure18;
  }

  public MealDetails strMeasure19(String strMeasure19) {
    this.strMeasure19 = strMeasure19;
    return this;
  }

   /**
   * Get strMeasure19
   * @return strMeasure19
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure19() {
    return strMeasure19;
  }

  public void setStrMeasure19(String strMeasure19) {
    this.strMeasure19 = strMeasure19;
  }

  public MealDetails strMeasure20(String strMeasure20) {
    this.strMeasure20 = strMeasure20;
    return this;
  }

   /**
   * Get strMeasure20
   * @return strMeasure20
  **/
  @ApiModelProperty(value = "")
  public String getStrMeasure20() {
    return strMeasure20;
  }

  public void setStrMeasure20(String strMeasure20) {
    this.strMeasure20 = strMeasure20;
  }

  public MealDetails strSource(String strSource) {
    this.strSource = strSource;
    return this;
  }

   /**
   * Get strSource
   * @return strSource
  **/
  @ApiModelProperty(value = "")
  public String getStrSource() {
    return strSource;
  }

  public void setStrSource(String strSource) {
    this.strSource = strSource;
  }

  public MealDetails strImageSource(String strImageSource) {
    this.strImageSource = strImageSource;
    return this;
  }

   /**
   * Get strImageSource
   * @return strImageSource
  **/
  @ApiModelProperty(value = "")
  public String getStrImageSource() {
    return strImageSource;
  }

  public void setStrImageSource(String strImageSource) {
    this.strImageSource = strImageSource;
  }

  public MealDetails strCreativeCommonsConfirmed(String strCreativeCommonsConfirmed) {
    this.strCreativeCommonsConfirmed = strCreativeCommonsConfirmed;
    return this;
  }

   /**
   * Get strCreativeCommonsConfirmed
   * @return strCreativeCommonsConfirmed
  **/
  @ApiModelProperty(value = "")
  public String getStrCreativeCommonsConfirmed() {
    return strCreativeCommonsConfirmed;
  }

  public void setStrCreativeCommonsConfirmed(String strCreativeCommonsConfirmed) {
    this.strCreativeCommonsConfirmed = strCreativeCommonsConfirmed;
  }

  public MealDetails dateModified(String dateModified) {
    this.dateModified = dateModified;
    return this;
  }

   /**
   * Get dateModified
   * @return dateModified
  **/
  @ApiModelProperty(value = "")
  public String getDateModified() {
    return dateModified;
  }

  public void setDateModified(String dateModified) {
    this.dateModified = dateModified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MealDetails mealDetails = (MealDetails) o;
    return Objects.equals(this.idMeal, mealDetails.idMeal) &&
        Objects.equals(this.strMeal, mealDetails.strMeal) &&
        Objects.equals(this.strDrinkAlternate, mealDetails.strDrinkAlternate) &&
        Objects.equals(this.strCategory, mealDetails.strCategory) &&
        Objects.equals(this.strArea, mealDetails.strArea) &&
        Objects.equals(this.strInstructions, mealDetails.strInstructions) &&
        Objects.equals(this.strMealThumb, mealDetails.strMealThumb) &&
        Objects.equals(this.strTags, mealDetails.strTags) &&
        Objects.equals(this.strYoutube, mealDetails.strYoutube) &&
        Objects.equals(this.strIngredient1, mealDetails.strIngredient1) &&
        Objects.equals(this.strIngredient2, mealDetails.strIngredient2) &&
        Objects.equals(this.strIngredient3, mealDetails.strIngredient3) &&
        Objects.equals(this.strIngredient4, mealDetails.strIngredient4) &&
        Objects.equals(this.strIngredient5, mealDetails.strIngredient5) &&
        Objects.equals(this.strIngredient6, mealDetails.strIngredient6) &&
        Objects.equals(this.strIngredient7, mealDetails.strIngredient7) &&
        Objects.equals(this.strIngredient8, mealDetails.strIngredient8) &&
        Objects.equals(this.strIngredient9, mealDetails.strIngredient9) &&
        Objects.equals(this.strIngredient10, mealDetails.strIngredient10) &&
        Objects.equals(this.strIngredient11, mealDetails.strIngredient11) &&
        Objects.equals(this.strIngredient12, mealDetails.strIngredient12) &&
        Objects.equals(this.strIngredient13, mealDetails.strIngredient13) &&
        Objects.equals(this.strIngredient14, mealDetails.strIngredient14) &&
        Objects.equals(this.strIngredient15, mealDetails.strIngredient15) &&
        Objects.equals(this.strIngredient16, mealDetails.strIngredient16) &&
        Objects.equals(this.strIngredient17, mealDetails.strIngredient17) &&
        Objects.equals(this.strIngredient18, mealDetails.strIngredient18) &&
        Objects.equals(this.strIngredient19, mealDetails.strIngredient19) &&
        Objects.equals(this.strIngredient20, mealDetails.strIngredient20) &&
        Objects.equals(this.strMeasure1, mealDetails.strMeasure1) &&
        Objects.equals(this.strMeasure2, mealDetails.strMeasure2) &&
        Objects.equals(this.strMeasure3, mealDetails.strMeasure3) &&
        Objects.equals(this.strMeasure4, mealDetails.strMeasure4) &&
        Objects.equals(this.strMeasure5, mealDetails.strMeasure5) &&
        Objects.equals(this.strMeasure6, mealDetails.strMeasure6) &&
        Objects.equals(this.strMeasure7, mealDetails.strMeasure7) &&
        Objects.equals(this.strMeasure8, mealDetails.strMeasure8) &&
        Objects.equals(this.strMeasure9, mealDetails.strMeasure9) &&
        Objects.equals(this.strMeasure10, mealDetails.strMeasure10) &&
        Objects.equals(this.strMeasure11, mealDetails.strMeasure11) &&
        Objects.equals(this.strMeasure12, mealDetails.strMeasure12) &&
        Objects.equals(this.strMeasure13, mealDetails.strMeasure13) &&
        Objects.equals(this.strMeasure14, mealDetails.strMeasure14) &&
        Objects.equals(this.strMeasure15, mealDetails.strMeasure15) &&
        Objects.equals(this.strMeasure16, mealDetails.strMeasure16) &&
        Objects.equals(this.strMeasure17, mealDetails.strMeasure17) &&
        Objects.equals(this.strMeasure18, mealDetails.strMeasure18) &&
        Objects.equals(this.strMeasure19, mealDetails.strMeasure19) &&
        Objects.equals(this.strMeasure20, mealDetails.strMeasure20) &&
        Objects.equals(this.strSource, mealDetails.strSource) &&
        Objects.equals(this.strImageSource, mealDetails.strImageSource) &&
        Objects.equals(this.strCreativeCommonsConfirmed, mealDetails.strCreativeCommonsConfirmed) &&
        Objects.equals(this.dateModified, mealDetails.dateModified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idMeal, strMeal, strDrinkAlternate, strCategory, strArea, strInstructions, strMealThumb, strTags, strYoutube, strIngredient1, strIngredient2, strIngredient3, strIngredient4, strIngredient5, strIngredient6, strIngredient7, strIngredient8, strIngredient9, strIngredient10, strIngredient11, strIngredient12, strIngredient13, strIngredient14, strIngredient15, strIngredient16, strIngredient17, strIngredient18, strIngredient19, strIngredient20, strMeasure1, strMeasure2, strMeasure3, strMeasure4, strMeasure5, strMeasure6, strMeasure7, strMeasure8, strMeasure9, strMeasure10, strMeasure11, strMeasure12, strMeasure13, strMeasure14, strMeasure15, strMeasure16, strMeasure17, strMeasure18, strMeasure19, strMeasure20, strSource, strImageSource, strCreativeCommonsConfirmed, dateModified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MealDetails {\n");
    
    sb.append("    idMeal: ").append(toIndentedString(idMeal)).append("\n");
    sb.append("    strMeal: ").append(toIndentedString(strMeal)).append("\n");
    sb.append("    strDrinkAlternate: ").append(toIndentedString(strDrinkAlternate)).append("\n");
    sb.append("    strCategory: ").append(toIndentedString(strCategory)).append("\n");
    sb.append("    strArea: ").append(toIndentedString(strArea)).append("\n");
    sb.append("    strInstructions: ").append(toIndentedString(strInstructions)).append("\n");
    sb.append("    strMealThumb: ").append(toIndentedString(strMealThumb)).append("\n");
    sb.append("    strTags: ").append(toIndentedString(strTags)).append("\n");
    sb.append("    strYoutube: ").append(toIndentedString(strYoutube)).append("\n");
    sb.append("    strIngredient1: ").append(toIndentedString(strIngredient1)).append("\n");
    sb.append("    strIngredient2: ").append(toIndentedString(strIngredient2)).append("\n");
    sb.append("    strIngredient3: ").append(toIndentedString(strIngredient3)).append("\n");
    sb.append("    strIngredient4: ").append(toIndentedString(strIngredient4)).append("\n");
    sb.append("    strIngredient5: ").append(toIndentedString(strIngredient5)).append("\n");
    sb.append("    strIngredient6: ").append(toIndentedString(strIngredient6)).append("\n");
    sb.append("    strIngredient7: ").append(toIndentedString(strIngredient7)).append("\n");
    sb.append("    strIngredient8: ").append(toIndentedString(strIngredient8)).append("\n");
    sb.append("    strIngredient9: ").append(toIndentedString(strIngredient9)).append("\n");
    sb.append("    strIngredient10: ").append(toIndentedString(strIngredient10)).append("\n");
    sb.append("    strIngredient11: ").append(toIndentedString(strIngredient11)).append("\n");
    sb.append("    strIngredient12: ").append(toIndentedString(strIngredient12)).append("\n");
    sb.append("    strIngredient13: ").append(toIndentedString(strIngredient13)).append("\n");
    sb.append("    strIngredient14: ").append(toIndentedString(strIngredient14)).append("\n");
    sb.append("    strIngredient15: ").append(toIndentedString(strIngredient15)).append("\n");
    sb.append("    strIngredient16: ").append(toIndentedString(strIngredient16)).append("\n");
    sb.append("    strIngredient17: ").append(toIndentedString(strIngredient17)).append("\n");
    sb.append("    strIngredient18: ").append(toIndentedString(strIngredient18)).append("\n");
    sb.append("    strIngredient19: ").append(toIndentedString(strIngredient19)).append("\n");
    sb.append("    strIngredient20: ").append(toIndentedString(strIngredient20)).append("\n");
    sb.append("    strMeasure1: ").append(toIndentedString(strMeasure1)).append("\n");
    sb.append("    strMeasure2: ").append(toIndentedString(strMeasure2)).append("\n");
    sb.append("    strMeasure3: ").append(toIndentedString(strMeasure3)).append("\n");
    sb.append("    strMeasure4: ").append(toIndentedString(strMeasure4)).append("\n");
    sb.append("    strMeasure5: ").append(toIndentedString(strMeasure5)).append("\n");
    sb.append("    strMeasure6: ").append(toIndentedString(strMeasure6)).append("\n");
    sb.append("    strMeasure7: ").append(toIndentedString(strMeasure7)).append("\n");
    sb.append("    strMeasure8: ").append(toIndentedString(strMeasure8)).append("\n");
    sb.append("    strMeasure9: ").append(toIndentedString(strMeasure9)).append("\n");
    sb.append("    strMeasure10: ").append(toIndentedString(strMeasure10)).append("\n");
    sb.append("    strMeasure11: ").append(toIndentedString(strMeasure11)).append("\n");
    sb.append("    strMeasure12: ").append(toIndentedString(strMeasure12)).append("\n");
    sb.append("    strMeasure13: ").append(toIndentedString(strMeasure13)).append("\n");
    sb.append("    strMeasure14: ").append(toIndentedString(strMeasure14)).append("\n");
    sb.append("    strMeasure15: ").append(toIndentedString(strMeasure15)).append("\n");
    sb.append("    strMeasure16: ").append(toIndentedString(strMeasure16)).append("\n");
    sb.append("    strMeasure17: ").append(toIndentedString(strMeasure17)).append("\n");
    sb.append("    strMeasure18: ").append(toIndentedString(strMeasure18)).append("\n");
    sb.append("    strMeasure19: ").append(toIndentedString(strMeasure19)).append("\n");
    sb.append("    strMeasure20: ").append(toIndentedString(strMeasure20)).append("\n");
    sb.append("    strSource: ").append(toIndentedString(strSource)).append("\n");
    sb.append("    strImageSource: ").append(toIndentedString(strImageSource)).append("\n");
    sb.append("    strCreativeCommonsConfirmed: ").append(toIndentedString(strCreativeCommonsConfirmed)).append("\n");
    sb.append("    dateModified: ").append(toIndentedString(dateModified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

